# Generated by Django 3.2.5 on 2022-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaceName', models.CharField(max_length=50, verbose_name='大会名')),
                ('Category', models.CharField(choices=[('swim', '水泳大会'), ('bike', 'ロードレース'), ('run', '陸上大会')], max_length=30, verbose_name='大会カテゴリ')),
                ('RaceDate', models.DateTimeField(verbose_name='大会日')),
                ('Distance', models.IntegerField(verbose_name='距離(m)')),
                ('TimeLimit', models.IntegerField(blank=True, verbose_name='時間制限(min)')),
                ('TargetTime', models.IntegerField(blank=True, verbose_name='目標タイム(min)')),
            ],
        ),
    ]
