# Generated by Django 3.2.5 on 2022-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='Remarks',
            field=models.TextField(blank=True, max_length=1000, verbose_name='備考'),
        ),
    ]
