# Generated by Django 2.2.5 on 2022-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Category',
            field=models.CharField(choices=[('bike_sun', 'バイク_晴'), ('bike_rai', 'バイク_雨'), ('run_sun', 'ラン_晴'), ('run_rai', 'ラン_雨'), ('swim_kick', 'スイム_キック'), ('swim_pull', 'スイム_プル'), ('swim_main', 'スイム_メイン')], max_length=30, verbose_name='練習カテゴリ'),
        ),
    ]
