# Generated by Django 2.2.5 on 2022-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0004_auto_20220527_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='LapTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='目標タイム(sec)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='NumLap',
            field=models.IntegerField(blank=True, null=True, verbose_name='周回数'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Remarks',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='race',
            name='Remarks',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='race',
            name='TargetTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='目標タイム(min)'),
        ),
        migrations.AlterField(
            model_name='race',
            name='TimeLimit',
            field=models.IntegerField(blank=True, null=True, verbose_name='時間制限(min)'),
        ),
    ]
